<a href="https://colab.research.google.com/github/gp1313/WinterSchoolOfAI2018/blob/master/EightPointMethod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Eight Point Method Assignment**

The following exercise tells you how to compute the Essential matrix using the 8 point method.



Generate 50 points using uniform distribution
np.random.uniform()
In the range 0 to 1

2. Add [ 1 4 3] to all the points.

3. Project the points into two cameras using the two projection matrices.

P1 = [ [1 0 0 0], [0 1 0 0], [0 0 1 0], [0 0 0 1]]


Generate a rotation and translation
R =[ 0.8660    0.2500    0.4330
         0    0.8660   -0.5000
      -0.5000    0.4330    0.7500]

T = [ -0.4 0.3 0.6]

P2 = [[ R | t ], [ 0 0 0 1]]

4. Use corresponding points in the image to generate 8 point equations

5. Formulate two equations:

Ax = 0 and
Ax = b

6. Solve using svd and pseudoinverse

7. What are the values?

8. Use python-opencv to decompose the essential matrix:

R1, R2, T = cv2.decomposeEssentialMat(E)

Step One : Generate 50 random 3D points

In [0]:
import numpy as np

## 1. Generate 3d 50 points using uniform distribution

In [0]:
oReferenceNP = np.array([1, 4, 3], dtype=float)

In [0]:
oReferenceNP

array([1., 4., 3.])

In [0]:
oRandomMatrix = np.random.uniform(size=(50, 3))

In [0]:
#oRandomMatrix

## 2. Add [ 1 4 3] to all the points -> 1 to x, 4 to y and 3 to z.

In [0]:
o50PointsMatrixNP = oRandomMatrix + oReferenceNP # Using broadcsting approach

In [0]:
o50PointsMatrixNP.shape

(50, 3)

In [0]:
oOneArrayNP = np.ones(shape=(50, 1))

In [0]:
o50HomogenousPointsMatrixNP = np.concatenate((o50PointsMatrixNP, oOneArrayNP), axis=1)

In [0]:
# o50HomogenousPointsMatrixNP

## 3. Project the points into two cameras using the two projection matrices.

P1 = [ [1 0 0 0], [0 1 0 0], [0 0 1 0]]

In [0]:
oFirstProjectionMatrixNP = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0]], dtype=float)

In [0]:
oFirstProjectionMatrixNP.shape

(3, 4)

In [0]:
oFirstProjectedPointsNP = np.matmul(o50HomogenousPointsMatrixNP, oFirstProjectionMatrixNP.T)

In [0]:
oFirstProjectedPointsNP

array([[1.24154571, 4.54196954, 3.93923003],
       [1.2138547 , 4.01792087, 3.1483685 ],
       [1.6790228 , 4.0803074 , 3.44976783],
       [1.96826969, 4.77700946, 3.6463029 ],
       [1.6975823 , 4.48955602, 3.70263183],
       [1.36451344, 4.3270391 , 3.89838045],
       [1.43229362, 4.94590754, 3.69329619],
       [1.37256408, 4.13398291, 3.36021476],
       [1.04074668, 4.3673861 , 3.94643119],
       [1.16738646, 4.15900665, 3.74654415],
       [1.30378824, 4.22879016, 3.25061715],
       [1.8644055 , 4.06985148, 3.21537997],
       [1.2107832 , 4.93367641, 3.13634715],
       [1.78329724, 4.15760481, 3.60340765],
       [1.24900441, 4.92679552, 3.54986671],
       [1.95048972, 4.57616074, 3.24039509],
       [1.67514181, 4.56107487, 3.34756258],
       [1.50886987, 4.56179987, 3.74130292],
       [1.35241555, 4.39404821, 3.18178119],
       [1.00297974, 4.56761745, 3.84993808],
       [1.50698903, 4.04605909, 3.16271798],
       [1.43519853, 4.46723648, 3.77449273],
       [1.

R =[ 0.8660    0.2500    0.4330
         0    0.8660   -0.5000
      -0.5000    0.4330    0.7500]

T = [ -0.4 0.3 0.6]

P2 = [[ R | t ], [ 0 0 0 1]] -> second camera

In [0]:
oRotationTransNP = np.array([ [0.8660, 0.2500, 0.4330, -0.4],
                               [0,0.8660,-0.5000, 0.3],
                               [-0.5000, 0.4330, 0.7500, 0.6]],
                              dtype=float)

In [0]:
oRotationTransNP

array([[ 0.866,  0.25 ,  0.433, -0.4  ],
       [ 0.   ,  0.866, -0.5  ,  0.3  ],
       [-0.5  ,  0.433,  0.75 ,  0.6  ]])

In [0]:
oSecondProjectiveMatrixNP = oRotationTransNP # np.concatenate((oRotationTransNP, np.array([[0, 0, 0, 1]])), axis=0)

In [0]:
oSecondProjectiveMatrixNP.shape

(3, 4)

In [0]:
oSecondProjectedPointsNP = np.matmul(o50HomogenousPointsMatrixNP, oSecondProjectiveMatrixNP.T)

In [0]:
oSecondProjectedPointsNP 

array([[3.51635758, 2.2637306 , 4.90032248],
       [3.01892195, 2.20533522, 4.09410876],
       [3.56786006, 2.10866229, 4.11458758],
       [4.07762307, 2.61373874, 4.41903742],
       [3.79573486, 2.33663959, 4.47216048],
       [3.55142715, 2.09802564, 4.71513655],
       [3.67604042, 2.73650783, 4.7954033 ],
       [3.27710921, 2.19992182, 4.22389363],
       [3.30193785, 2.10894076, 4.93052823],
       [3.27296196, 2.02842768, 4.62706476],
       [3.19379538, 2.33682371, 4.21713488],
       [3.62429756, 2.2168014 , 3.84157792],
       [3.23999567, 3.0043902 , 4.48315065],
       [3.74401213, 2.09878194, 4.21115   ],
       [3.45042899, 2.79167157, 4.77120029],
       [3.83625536, 2.64275766, 4.03652906],
       [3.64043612, 2.57610955, 4.24804645],
       [3.66711544, 2.37986723, 4.6268016 ],
       [3.24741518, 2.51435515, 4.21275099],
       [3.27750801, 2.33058767, 4.96374205],
       [3.28602416, 2.22252818, 3.97048756],
       [3.5940464 , 2.28138043, 4.64758368],
       [3.

In [0]:
oSecondProjectedPointsNP[..., 2].ravel()

array([4.90032248, 4.09410876, 4.11458758, 4.41903742, 4.47216048,
       4.71513655, 4.7954033 , 4.22389363, 4.93052823, 4.62706476,
       4.21713488, 3.84157792, 4.48315065, 4.21115   , 4.77120029,
       4.03652906, 4.24804645, 4.6268016 , 4.21275099, 4.96374205,
       3.97048756, 4.64758368, 4.64244825, 4.81330094, 4.22209814,
       4.02787958, 4.39249912, 4.10144611, 4.169346  , 4.56974541,
       4.05056308, 4.28140604, 4.23756895, 3.93911637, 4.19139254,
       4.02937101, 4.0537012 , 4.77643937, 4.68728291, 4.13016153,
       4.5348674 , 4.8693183 , 4.85518856, 4.53332362, 4.31307042,
       5.0257145 , 4.34763341, 4.84342807, 5.00808167, 4.65519716])

In [0]:
oNormalizedFirstProjectedPointsNP = np.divide(oFirstProjectedPointsNP, oFirstProjectedPointsNP[..., 2].ravel().reshape(50, 1))

In [0]:
oNormalizedSecondProjectedPointsNP = np.divide(oSecondProjectedPointsNP, oSecondProjectedPointsNP[..., 2].ravel().reshape(50, 1))

In [0]:
oNormalizedSecondProjectedPointsNP

array([[0.71757677, 0.46195544, 1.        ],
       [0.73738196, 0.53866063, 1.        ],
       [0.86712459, 0.51248448, 1.        ],
       [0.92274011, 0.59147242, 1.        ],
       [0.84874746, 0.52248563, 1.        ],
       [0.75319709, 0.44495544, 1.        ],
       [0.76657586, 0.57065228, 1.        ],
       [0.77585032, 0.52082794, 1.        ],
       [0.66969252, 0.4277312 , 1.        ],
       [0.70735166, 0.43838325, 1.        ],
       [0.75733773, 0.55412591, 1.        ],
       [0.94343981, 0.57705491, 1.        ],
       [0.72270506, 0.67015152, 1.        ],
       [0.88907119, 0.49838689, 1.        ],
       [0.7231784 , 0.58510886, 1.        ],
       [0.95038467, 0.65471043, 1.        ],
       [0.85696712, 0.60642217, 1.        ],
       [0.79258109, 0.51436552, 1.        ],
       [0.77085382, 0.596844  , 1.        ],
       [0.66028975, 0.46952232, 1.        ],
       [0.82761225, 0.55976203, 1.        ],
       [0.77331505, 0.49087452, 1.        ],
       [0.

In [0]:
oNormalizedFirstProjectedPointsNP

array([[0.31517472, 1.15300947, 1.        ],
       [0.38555039, 1.27619142, 1.        ],
       [0.48670603, 1.18277739, 1.        ],
       [0.53979873, 1.31009672, 1.        ],
       [0.45847991, 1.21253104, 1.        ],
       [0.35002059, 1.10995814, 1.        ],
       [0.38780903, 1.33915811, 1.        ],
       [0.4084751 , 1.23027342, 1.        ],
       [0.26371844, 1.10666724, 1.        ],
       [0.31159021, 1.11009145, 1.        ],
       [0.40108945, 1.30091917, 1.        ],
       [0.57983987, 1.26574512, 1.        ],
       [0.38604885, 1.57306452, 1.        ],
       [0.4948919 , 1.15379808, 1.        ],
       [0.35184544, 1.38788184, 1.        ],
       [0.6019296 , 1.41222308, 1.        ],
       [0.50040642, 1.36250623, 1.        ],
       [0.40330064, 1.21930781, 1.        ],
       [0.42504983, 1.38100263, 1.        ],
       [0.26051841, 1.18641322, 1.        ],
       [0.47648543, 1.27929809, 1.        ],
       [0.38023614, 1.18353294, 1.        ],
       [0.

## 4. Use corresponding points in the image to generate 8 point equations

A = [u2 * u1,  u2 v1 , u2 , v2 * u1 , v2 * v1 , v2 , u1 * v1 , 1]


In [0]:
u1 = oNormalizedFirstProjectedPointsNP[:,0].reshape(50, 1)
v1 = oNormalizedFirstProjectedPointsNP[:,1].reshape(50, 1)
v1 = oNormalizedSecondProjectedPointsNP[:,0].reshape(50, 1)
v2 = oNormalizedSecondProjectedPointsNP[:,1].reshape(50, 1)
ones = np.ones(shape=(50, 1))

In [0]:
o2DPointsMatrixNP = np.concatenate((u2 * u1,  u2 * v1 , u2 , v2 * u1 , v2 * v1 , v2 , u1 ,  v1 , ones), axis=1)

In [0]:
o2DPointsMatrixNP.shape

(50, 9)

## 5. Formulate two equations:
Ax = 0 and
Ax = b

In [0]:
u, s, vh = np.linalg.svd(o2DPointsMatrixNP, full_matrices=True)

In [0]:
s.shape

(9,)

In [0]:
u.shape

(50, 50)

In [0]:
v = vh.T

In [0]:
x = v[:, -1]

In [0]:
x

array([ 0.33021491, -0.33070118,  0.10785558, -0.58042068,  0.60852718,
       -0.20885536, -0.10732739,  0.08528278, -0.01885844])

In [0]:
import cv2

In [0]:
R1, R2, T = cv2.decomposeEssentialMat(x)

In [0]:
T

array([[0.80788802],
       [0.37555083],
       [0.45417895]])

In [0]:
R2

array([[ 0.15789671, -0.00444493,  0.98744563],
       [ 0.91762248,  0.37003356, -0.14506601],
       [-0.36474322,  0.92900775,  0.06250584]])

In [0]:
R1

array([[ 0.33736781,  0.90493497,  0.2593755 ],
       [-0.68739627,  0.04856379,  0.72465711],
       [ 0.64317131, -0.42276974,  0.63843278]])